# all constants
WIDTH, HEIGHT = 775, 700 ## board size is 700, 700
LOWER_BOARDER = 75
CELL_WIDTH, CELL_HEIGHT = 5, 5
COLS = WIDTH // CELL_WIDTH
ROWS = (HEIGHT - LOWER_BOARDER) // CELL_HEIGHT
print(f"{ROWS=}, {COLS=}, {CELL_WIDTH=}, {CELL_HEIGHT=}")