"""

NEED TO FIND A WAY TO IMPORT FROM ABOVE
"""


# all constants
WIDTH, HEIGHT = 775, 700
LOWER_BOARDER = 75
CELL_WIDTH, CELL_HEIGHT = 5, 5
COLS = WIDTH // CELL_WIDTH
ROWS = (HEIGHT - LOWER_BOARDER) // CELL_HEIGHT
